userid-default: admin
password-default: yggdrasil
redundant-network: false
ipaddr-mgmt-network: 192.168.3.0/24
ipaddr-mgmt-switch:
    rack1: 192.168.3.5
userid-mgmt-switch: admin
password-mgmt-switch: yggdrasil
ipaddr-data-switch:
    rack1: 192.168.3.6
userid-data-switch: admin
password-data-switch: yggdrasil
networks:
    openstack-mgmt-network:
        vlan: 10
        eth-port: eth10
    openstack-stg-network:
        vlan: 20
        eth-port: eth10
    openstack-tenant-network:
        vlan: 30
        eth-port: eth11
node-templates:
    controller1:
        hostname:
        userid-ipmi: ADMIN
        password-ipmi: ADMIN
        ports:
            ipmi:
                rack1:
                - 2
                - 3
                - 5
            pxe:
                rack1:
                - 20
                - 21
                - 23
            eth10:
                rack1:
                - 11
                - 12
                - 13
            eth11:
                rack1:
                - 41
                - 42
                - 43
        networks:
            - openstack-mgmt-network
            - openstack-stg-network
    controller2:
        hostname: power
        userid-ipmi: ADMIN
        password-ipmi: admin
        ports:
            ipmi:
                rack1:
                - 6
            pxe:
                rack1:
                - 24
            eth10:
                rack1:
                - 14
            eth11:
                rack1:
                - 15
        networks:
            - openstack-tenant-network
