userid-default: admin
password-default: yggdrasil
redundant-network: false
ipaddr-mgmt-network: 192.168.3.0/20
ipaddr-mgmt-switch:
-   rack1: 192.168.3.5
userid-mgmt-switch: admin
password-mgmt-switch: yggdrasil
ipaddr-leaf-switch:
-   rack1: 192.168.3.6
userid-leaf-switch: joeleaf
password-leaf-switch: joeleafpassword
networks:
    openstack-mgmt-network:
        vlan: 10
        eth-port: eth10
    openstack-stg-network:
        vlan: 20
        bridge-ports: eth10
    openstack-tenant-vxlan-network:
        vlan: 30
        eth-port: eth11
nodes_templates:
    controller1:
        hostname:
        userid-ipmi: ADMIN
        password-ipmi: ADMIN
        ipmi-ports:
            rack1:
            - 2
            - 3
            - 5
        pxe-ports:
            rack1:
            - 20
            - 21
            - 23
        eth10-ports:
            rack1:
            - 11
            - 12
            - 13
        eth11-ports:
            rack1:
            - 41
            - 42
            - 43
    controller2:
        hostname: power
        userid-ipmi: ADMIN
        password-ipmi: admin
        ipmi-ports:
            rack1:
            - 6
        pxe-ports:
            rack1:
            - 24
        eth10-ports:
            rack1:
            - 14
        eth11-ports:
            rack1:
            - 15
