---
# Copyright 2016, IBM US, Inc.

- name: Check for interface name collisions
  fail:
    msg: "The renaming of network interfaces on this host will fail because it already has interface {{ item }} which has the MAC address {{ hostvars[inventory_hostname]['ansible_' + item]['macaddress'] }}. This will prevent the interface with MAC address {{ name_interfaces.get(item) }} from being renamed to {{ item }}."
  when:
    - name_interfaces is defined
    - "{{ item in name_interfaces }}"
    - "{{ name_interfaces.get(item) != hostvars[inventory_hostname]['ansible_' + item]['macaddress'] }}"
  with_items: "{{ ansible_interfaces }}"

- name: Generate udev persistent net rules
  template:
    src: "{{ playbook_dir }}/templates/persistent-net-rules.j2"
    dest: /etc/udev/rules.d/99-persistent-net.rules
    owner: "root"
    group: "root"
    mode: "0644"
  register: wrote_netrules

- name: Generate interfaces file
  template:
    src: "{{ playbook_dir }}/templates/interfaces.j2"
    dest: "/etc/network/interfaces"
    owner: "root"
    group: "root"
    mode: "0644"
    backup: yes
  register: wrote_interfaces

- name: Reboot
  command: reboot
  when: wrote_netrules.changed or wrote_interfaces.changed

- name: Wait for system to come back up
  local_action: wait_for state=started delay="{{ reboot_delay_time }}" port=22 search_regex=OpenSSH timeout="{{ reboot_wait_interval }}" host="{{ inventory_hostname }}"
  when: wrote_netrules.changed or wrote_interfaces.changed

...
