---
# Copyright 2016, IBM US, Inc.

- name: Create inventory file target directory
  file:
    path: /var/oprc
    state: directory
    owner: root
    group: root
    mode: "0644"

- name: Transferring inventory file
  copy:
    src: /var/oprc/inventory.yml
    dest: /var/oprc/inventory.yml
    owner: root
    group: root
    mode: "0644"
...
