---
- hosts: deployer
  tasks:
    - command: "python {{ scripts_path }}/inventory.py {{ genesis_inventory }}"
      register: output
    - debug:
        msg: "{{ output.stdout }}"
    - fetch:
        src: "{{ output.stdout | to_nice_yaml( width=80 ) }}"
        dest: "{{ file }}.yaml"
        flat: yes
#    - fetch:
#        src: "{{ output.stdout }}"
#        dest: "{{ file }}.json"
#        flat: yes
