- hosts: deployer
  vars:
    log_level: ""
  tasks:

#    - name: "Copy OS installer images to container."
#      copy:
#        force: no
#        src: ~/os_images
#        dest: "{{ project_path }}"

    - shell: "ls {{ project_path }}/os_images/*.iso"
      register: iso_files

    - debug: var=project_path
    - debug:
        msg: "PATH = /mnt/{{ item | basename | regex_replace('^(.*).iso$', '\\1') }} NAME = {{ item | basename | regex_replace('^(.*).iso$', '\\1') }} ARCH = {{ item | basename | regex_replace('^.*-(.*).iso$', '\\1') }}"
      with_items: "{{ iso_files.stdout_lines }}"

    - name: "Mount OS installer images."
      mount:
        name: "/mnt/{{ item | basename | regex_replace('^(.*).iso$', '\\1') }}"
        src: "{{ item }}"
        fstype: iso9660
        opts: loop,ro
        state: mounted
      with_items:
        - "{{ iso_files.stdout_lines }}"
      become: yes
      become_method: sudo
    
    - command: "{{ python_executable }} {{ scripts_path }}/python/cobbler_add_distro.py {{ genesis_inventory }} /mnt/{{ item | basename | regex_replace('^(.*).iso$', '\\1') }} {{ item | basename | regex_replace('^(.*).iso$', '\\1') }}  {{ item | basename | regex_replace('^.*-(.*).iso$', '\\1') }} {{ log_level }}"
      with_items:
        - "{{ iso_files.stdout_lines }}"
      become: yes
      become_method: sudo

    - pause: seconds=10

    - name: "Unmount OS installer images."
      mount:
        name: "/mnt/{{ item | basename | regex_replace('^(.*).iso$', '\\1') }}"
        src: "{{ item }}"
        fstype: iso9660
        state: unmounted
      with_items:
        - "{{ iso_files.stdout_lines }}"
      become: yes
      become_method: sudo
    
