---
# Copyright 2016, IBM US, Inc.

- name: container/inv_modify_ipv4.yml
  hosts: deployer
  vars:
    log_level: ""
  tasks:
    - command: "{{ python_executable }} {{ scripts_path }}/python/inv_modify_ipv4.py {{ config }} {{ inventory }} {{ node_mgmt_ipv4_start }} {{ log_level }}"
      become: yes
      become_method: sudo
