---
# Copyright 2016, IBM US, Inc.

- name: container/inv_add_switches.yml
  hosts: deployer
  vars:
    log_level: ""
  tasks:
    - command: "{{ python_executable }} {{ scripts_path }}/python/inv_add_switches.py {{ config }} {{ inventory }} {{ log_level }}"
