---
# Copyright 2016, IBM US, Inc.

- name: container/inv_add_config_file.yml
  hosts: deployer
  tasks:
    - name: "Append config.yml to inventory.yml"
      shell: "cat {{ config }} >> {{ inventory }}"
