---
# Copyright 2016, IBM US, Inc.

- name: container/ipmi_set_bootdev.yml
  hosts: deployer
  vars:
    log_level: ""
    bootdev: pxe
    persistent: False
  tasks:
    - command: "{{ python_executable }} {{ scripts_path }}/python/ipmi_set_bootdev.py {{ inventory }} {{ bootdev }} {{ persistent }} {{ log_level }}"
      ignore_errors: yes
