---
# Copyright 2016, IBM US, Inc.

- name: Gather facts from localhost
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Include localhost variables
      include_vars: host_vars/localhost

- name: Configure interfaces
  hosts: all
  tasks:
    - include: tasks/create_interfaces.yml

- name: Transfer keys
  hosts: controllers:compute
  tasks:
    - include: tasks/transfer_keys.yml

- name: Transfer inventory file
  hosts: controllers
  tasks:
    - include: tasks/transfer_inventory.yml

- name: Prepare Cluster Configuration Software
  hosts: controllers[0]
  tasks:
    - include: tasks/os_services_install.yml
