---
# Copyright 2016 IBM Corp.
#
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- include: lxc-update.yml
- include: container/cobbler/cobbler_install.yml
- include: pause.yml message="Please reset BMC interfaces to obtain DHCP leases"
- include: container/set_data_switch_config.yml log_level=info
- include: container/inv_add_switches.yml log_level=info
- include: container/inv_add_ipmi_ports.yml log_level=info
- include: container/ipmi_set_bootdev.yml log_level=info bootdev=network persistent=False
- include: container/ipmi_power_on.yml log_level=info
- include: pause.yml minutes=20 message="Power-on Nodes"
- include: container/inv_add_ipmi_data.yml log_level=info
- include: container/inv_add_pxe_ports.yml log_level=info
- include: container/ipmi_power_off.yml log_level=info
- include: container/inv_modify_ipv4.yml log_level=info
- include: container/cobbler/cobbler_add_distros.yml
- include: container/cobbler/cobbler_add_profiles.yml
- include: container/cobbler/cobbler_add_systems.yml
- include: container/inv_add_config_file.yml
- include: container/allocate_ip_addresses.yml
- include: container/get_inv_file.yml dest=/var/oprc
- include: container/ipmi_set_bootdev.yml log_level=info bootdev=network persistent=False
- include: container/ipmi_power_on.yml log_level=info
- include: pause.yml minutes=5 message="Power-on Nodes"
- include: container/ipmi_set_bootdev.yml log_level=info bootdev=default persistent=True
