---
- hosts: localhost
  gather_facts: yes
- hosts: installer
  vars:
      project_path_local: "{{ hostvars['localhost']['ansible_env']['PWD'] | regex_replace('^(.+/yggdrasil).+?$', '\\1')}}"
      scripts_path_local: "{{ project_path_local }}/scripts"
  tasks:
    - debug:
        msg: "{{ item }}"
      with_items:
      - "Config file: {{ config }}"
    - apt:
        update_cache: yes
        upgrade: safe
      become: yes
      become_method: sudo
    - apt: name="{{ item }}"
      with_items:
      - python-pip 
      - python-dev
      - libffi-dev
      - libssl-dev
      - python-pysnmp4
      become: yes
      become_method: sudo
    - pip: name="{{ item }}"
      with_items:
      - pip
      - setuptools
      - wheel
      - virtualenv
      become: yes
      become_method: sudo
    - file:
        path: "{{ project_path }}"
        state: directory
    - command: virtualenv --no-wheel --system-site-packages {{ venv_path }}
    - command: >
        /bin/bash -c "
        source {{ venv_path }}/bin/activate &&
        pip install --ignore-installed pyaml orderedattrdict pysnmp pyghmi paramiko &&
        deactivate"
    - copy:
        src: "{{ config }}"
        dest: "{{ project_path }}"
    - copy:
        src: "{{ scripts_path_local }}"
        dest: "{{ project_path }}"
