---
- name: lxc-update.yml
  hosts: localhost
  gather_facts: yes

- hosts: installer
  vars:
    scripts_path_local: "{{ hostvars['localhost']['scripts_path_local'] }}"
    config_local: "{{ hostvars['localhost']['config_local'] }}"
  tasks:
    - debug:
        msg: "{{ item }}"
      with_items:
      - "Local Scripts Path: {{ scripts_path_local }}"
      - "Local Config file: {{ config_local }}"

    - name: "Update apt cache and upgrade (safe)"
      apt:
        update_cache: yes
        upgrade: safe
      become: yes
      become_method: sudo

    - name: "Install distro packages"
      apt: name="{{ item }}"
      with_items:
      - python-pip 
      - python-dev
      - libffi-dev
      - libssl-dev
      - python-pysnmp4
      - ipmitool
      - fping
      become: yes
      become_method: sudo

    - name: "Install python pip packages"
      pip: name="{{ item }}"
      with_items:
      - pip
      - setuptools
      - wheel
      - virtualenv
      become: yes
      become_method: sudo

    - name: "Create project root directory"
      file:
        path: "{{ project_path }}"
        state: directory

    - name: "Create python virtual environment"
      command: virtualenv --no-wheel --system-site-packages {{ venv_path }}

    - name: "Activate python venv and install pip packages"
      command: >
        /bin/bash -c "
        source {{ venv_path }}/bin/activate &&
        pip install --ignore-installed pyaml orderedattrdict pysnmp pyghmi paramiko &&
        deactivate"

    - name: "Copy config file into deployment container"
      copy:
        src: "{{ config_local }}"
        dest: "{{ project_path }}"

    - name: "Copy scripts into deployment container"
      copy:
        src: "{{ scripts_path_local }}"
        dest: "{{ project_path }}"

    - name: "Create log file"
      file:
        path: "{{ project_path }}/log.txt"
        state: touch
        mode: 0755
