---
- hosts: localhost
  gather_facts: yes
- hosts: installer
  vars:
    scripts_path_local: "{{ hostvars['localhost']['scripts_path_local'] }}"
    config_local: "{{ hostvars['localhost']['config_local'] }}"
  tasks:
    - debug:
        msg: "{{ item }}"
      with_items:
      - "Local Scripts Path: {{ scripts_path_local }}"
      - "Local Config file: {{ config_local }}"
    - apt:
        update_cache: yes
        upgrade: safe
      become: yes
      become_method: sudo
    - apt: name="{{ item }}"
      with_items:
      - python-pip 
      - python-dev
      - libffi-dev
      - libssl-dev
      - python-pysnmp4
      - ipmitool
      become: yes
      become_method: sudo
    - pip: name="{{ item }}"
      with_items:
      - pip
      - setuptools
      - wheel
      - virtualenv
      become: yes
      become_method: sudo
    - file:
        path: "{{ project_path }}"
        state: directory
    - command: virtualenv --no-wheel --system-site-packages {{ venv_path }}
    - command: >
        /bin/bash -c "
        source {{ venv_path }}/bin/activate &&
        pip install --ignore-installed pyaml orderedattrdict pysnmp pyghmi paramiko &&
        deactivate"
    - copy:
        src: "{{ config_local }}"
        dest: "{{ project_path }}"
    - copy:
        src: "{{ scripts_path_local }}"
        dest: "{{ project_path }}"
    - file:
        path: "{{ project_path }}/log.txt"
        state: touch
        mode: 0755
