---
- hosts: localhost
  gather_facts: yes

- name: container/cobbler/cobbler_add_distros.yml
  hosts: deployer
  vars:
    log_level: ""
  tasks:

    - name: "Restore original /etc/cobbler/pxe/pxedefault.template file"
      copy:
        remote_src: True
        src: /etc/cobbler/pxe/pxedefault.template.orig
        dest: /etc/cobbler/pxe/pxedefault.template
      become: yes
      become_method: sudo

    - name: "Register list of *.iso files"
      find:
        paths: "{{ project_path }}/os_images"
        patterns: "*[!mini].iso"
      register: iso_files

    - name: "Register list of *.mini.iso files"
      find:
        paths: "{{ project_path }}/os_images"
        patterns: "*.mini.iso"
      register: mini_iso_files

    - name: "Register list of *.seed files"
      find:
        paths: "{{ project_path }}/os_images/config"
        patterns: "*.seed"
      register: seed_files

    - name: "Register list of *.list files"
      find:
        paths: "{{ project_path }}/os_images/config"
        patterns: "*.list"
      register: list_files

    - name: "Register list of *.cfg files"
      find:
        paths: "{{ project_path }}/os_images/config"
        patterns: "*.cfg"
      register: cfg_files

    - name: "Mount Distro installer images"
      mount:
        name: "/mnt/{{ item.path | basename | regex_replace('^(.*).iso$', '\\1') }}"
        src: "{{ item.path }}"
        fstype: iso9660
        opts: loop,ro
        state: mounted
      with_items:
        - "{{ iso_files.files }}"
        - "{{ mini_iso_files.files }}"
      become: yes
      become_method: sudo

    - name: "Copy distro images to http repo directory" 
      command: "rsync -a /mnt/{{ item.path | basename | regex_replace('^(.*).iso$', '\\1') }}/ /var/www/html/{{ item.path | basename | regex_replace('^(.*).iso$', '\\1') }}/"
      with_items:
        - "{{ iso_files.files }}"
      become: yes
      become_method: sudo
 
    - name: "Copy \"mini\" netboot files to web repo directory" 
      command: "rsync -a /mnt/{{ item.path | basename | regex_replace('^(.*).iso$', '\\1') }}/install/ /var/www/html/{{ item.path | basename | regex_replace('^(.*).mini.iso$', '\\1') }}/install/netboot/"
      with_items:
        - "{{ mini_iso_files.files }}"
      become: yes
      become_method: sudo
    
    - name: "Register default user id"
      shell: "grep userid-default {{ config }} | awk '{print $2}'"
      register: userid_default

    - name: "Update preseed configurations with default user id"
      replace:
        dest: "{{ item.path }}"
        regexp: "defaultuser"
        replace: "{{ userid_default.stdout }}"
      with_items:
        - "{{ seed_files.files }}"
      when: userid_default.stdout != ""
      become: yes
      become_method: sudo

    - name: "Register default password"
      shell: "grep password-default {{ config }} | awk '{print $2}'"
      register: password_default

    - name: "Update preseed configurations with default user password"
      replace:
        dest: "{{ item.path }}"
        regexp: "passw0rd"
        replace: "{{ password_default.stdout }}"
      with_items:
        - "{{ seed_files.files }}"
      when: password_default.stdout != ""
      become: yes
      become_method: sudo

    - name: "Copy preseed & kickstart configurations to cobbler kickstart directory"
      copy:
        src: "{{ item.path }}"
        remote_src: True
        dest: /var/lib/cobbler/kickstarts/
      with_items:
        - "{{ cfg_files.files }}"
        - "{{ seed_files.files }}"
      become: yes
      become_method: sudo

    - name: "Copy apt source lists to web repo directory" 
      copy:
        src: "{{ item.path }}"
        remote_src: True
        dest: "/var/www/html/{{ item.path | basename | regex_replace('^(.*).sources.list$', '\\1') }}/sources.list"
      with_items:
        - "{{ list_files.files }}"
      become: yes
      become_method: sudo

    - name: "Unmount distro installer images"
      mount:
        name: "/mnt/{{ item.path | basename | regex_replace('^(.*).iso$', '\\1') }}"
        src: "{{ item }}"
        fstype: iso9660
        state: unmounted
      with_items:
        - "{{ iso_files.files }}"
        - "{{ mini_iso_files.files }}"
      become: yes
      become_method: sudo
    
    - name: "Call python \"cobbler_add_distros.py\" script to import distros and create default profiles"
      command: "{{ python_executable }} {{ scripts_path }}/python/cobbler_add_distros.py /var/www/html/{{ item.path | basename | regex_replace('^(.*)[.]iso$', '\\1') }} {{ item.path | basename | regex_replace('^(.*)[.]iso$', '\\1') }} {{ log_level }}"
      with_items:
        - "{{ iso_files.files }}"
      become: yes
      become_method: sudo

